### ISSUE TITLE
Broken link to "Security Considerations for HTTP Signatures"

### ISSUE THREAD

**Issue by jyasskin** [w3c-ccg/http-signatures#14]
https://tools.ietf.org/html/draft-cavage-http-signatures-07#appendix-A has a [14] that doesn't go anywhere. I see the link to https://web-payments.org/specs/source/http-signatures-audit/ in your source.

**Comment by msporny** [comment]
Thanks, will fix.

**Comment by ioggstream** [comment]
@msporny iiuc that's fixed now. Can we close?

**Comment by msporny** [comment]
Confirmed, fixed. Thanks for the ping @ioggstream! :)
