### ISSUE TITLE
Broken references in Feedback section

### ISSUE THREAD

**Issue by jyasskin** [w3c-ccg/http-signatures#15]
https://tools.ietf.org/html/draft-cavage-http-signatures-07 has a feedback section saying:

> This specification is a joint work product of the W3C Digital   Verification Community Group [1] and the W3C Credentials Community   Group [2].  Feedback related to this specification should be sent to   public-credentials@w3.org [3].

However, there is no [1], and [2] and [3] link to:

>   [2] http://tools.ietf.org/html/rfc4648#section-4
>   [3] https://tools.ietf.org/html/rfc7540#section-8.1.2.3

**Comment by msporny** [comment]
These should be fixed to:

[1] https://w3c-dvcg.github.io/
[2] https://w3c-ccg.github.io/

and a working link for [3]. Will fix in next edit cycle.

**Comment by jyasskin** [comment]
I've reduced a very similar bug in xml2rfc: https://trac.tools.ietf.org/tools/xml2rfc/trac/ticket/335. Hopefully they'll fix it.

**Comment by msporny** [comment]
Great, thanks @jyasskin - even if they don't fix it, I'll find a workaround during the next edit cycle.

**Comment by ioggstream** [comment]
@msporny is this fixed?

**Comment by liamdennehy** [comment]
This was fixed in 90ba1341
