### ISSUE TITLE
Wrong section referenced for auth-param

### ISSUE THREAD

**Issue by jyasskin** [w3c-ccg/http-signatures#17]
https://tools.ietf.org/id/draft-cavage-http-signatures-07.html#sig-header says
> The sender is expected to transmit a header (as defined in RFC 7230, Section 3.2) where the "field-name" is "Signature", and the "field-value" contains one or more "auth-param"s (as defined in RFC 7235, Section 4.1)

However, auth-param is defined in https://tools.ietf.org/html/rfc7235#section-2.1.

**Comment by msporny** [comment]
Thank  you, will fix in next edit cycle.

**Comment by liamdennehy** [comment]
PR with fix, sorry for the delay :stuck_out_tongue:

**Comment by ioggstream** [comment]
@liamdennehy this is fixed, can we close?

**Comment by liamdennehy** [comment]
I don't have access to manage issues.

@jyasskin, @msporny ?

**Comment by msporny** [comment]
@liamdennehy wrote:
> I don't have access to manage issues.

Sent you an invite, @liamdennehy -- you will want to accept it.

https://github.com/orgs/w3c-dvcg/teams/http-signatures-developers

**Comment by liamdennehy** [comment]
Fixed in https://github.com/w3c-dvcg/http-signatures/pull/49
