### ISSUE TITLE
Mention the risks of (request-target) omitting :authority

### ISSUE THREAD

**Issue by jyasskin** [w3c-ccg/http-signatures#18]
The security considerations section should call out that `(request-target)` doesn't include the full URL, since 1589b3fb68d030ca72a4dbbf134335ac324586ca removed `:authority`, and say at least that this means that the key used to sign the request must not be trusted for more than one authority, to avoid attackers being able to get clients to trust a message signed as the wrong authority.

**Comment by msporny** [comment]
Please raise this issue in this repo: https://github.com/w3c-dvcg/http-signatures-audit

**Comment by jyasskin** [comment]
Done: https://github.com/w3c-dvcg/http-signatures-audit/issues/1

**Comment by msporny** [comment]
Thank you!
