### ISSUE TITLE
Omit rsa-sha1 from the Signature Algorithm Registry

### ISSUE THREAD

**Issue by jyasskin** [w3c-ccg/http-signatures#20]
https://tools.ietf.org/id/draft-cavage-http-signatures-07.html#sa-registry includes a deprecated algorithm using SHA1 in a totally new registry. Just omit it.

**Comment by msporny** [comment]
Agreed, will fix. Many parts of this spec are 5+ years old at this point.

**Comment by liamdennehy** [comment]
Do we still want to take this out, and optionally extend with SHA2-384 and SHA2-512?
I can put together a PR in short order...

**Comment by liamdennehy** [comment]
@jyasskin This has now been deprecated as you requested, can this issue be closed?
https://tools.ietf.org/html/draft-cavage-http-signatures-11#appendix-E.2

**Comment by liamdennehy** [comment]
v11 deprecates all legacy 'algorithm' values and replaces with a single SHA512 equivalent.
