### ISSUE TITLE
Test Vectors are wrong

### ISSUE THREAD

**Issue by msporny** [w3c-ccg/http-signatures#21]
@kislyuk wrote:
> The Test Values section of your RFC draft (https://tools.ietf.org/html/draft-cavage-http-signatures-07#appendix-C) is a mess, making it difficult and frustrating to create a conformance test suite.
>
> With the help of https://github.com/joyent/node-http-signature and by trial and error I figured out that you updated the timestamp ("Thu, 05 Jan 2012 21:31:40 GMT" to "Thu, 05 Jan 2014 21:31:40 GMT") and the request-target pseudo-header (from "request-line" to "(request-target)") without updating the signature values.

**Comment by msporny** [comment]
Thanks for the bug report. This will be updated in the next edit cycle.

**Comment by cwebber** [comment]
The above PR should fix things.  @lambadalambda (who also bumped into this) and I cross-checked our implementations and we both got the same results here.

**Comment by msporny** [comment]
New draft published: https://www.ietf.org/id/draft-cavage-http-signatures-08.txt
