### ISSUE TITLE
Use case: server signing other content

### ISSUE THREAD

**Issue by bblfish** [w3c-ccg/http-signatures#22]
I just found a discussion on HTTP WG discussing something requiring signatures and found
a link to this spec.  

https://tools.ietf.org/id/draft-yasskin-http-origin-signed-responses-00.html

**Comment by liamdennehy** [comment]
Yep, looks like this spec essentially realises the placeholder in that proposal's [Section 4.4](https://tools.ietf.org/id/draft-yasskin-http-origin-signed-responses-00.html#rfc.section.4.4). It's an interesting case, essentially a source could send a signed message to the CDN, and the CDN serves (partial) content using the author's Signature header. Obviously the Date would not be time served, but time presented to the CDN, but an alternate header could do that job (``Signature-Date``?).

The Digest spec already contemplates [serving partial content](https://tools.ietf.org/html/rfc3230#section-4.2) - essentially the digest is of the complete resource not just the range served, so no modifications to this spec required.

Worth writing this into the current spec, or overkill?

**Comment by ioggstream** [comment]
Hi @bblfish, can you explicit better this use-case or - if that's already covered - close the issue?

Thx++ :)

**Comment by liamdennehy** [comment]
With v11 introducing an explicit [``created``](https://tools.ietf.org/html/draft-cavage-http-signatures-11#section-2.1.4) field we can now tie individual signatures to metadata for that signature itself - independent of the ``Date`` header. I think this can close, but @bblfish if you feel this needs more work feel free to open a new issue.
