### ISSUE TITLE
Dead link to Signature Algorithms registry

### ISSUE THREAD

**Issue by cjslep** [w3c-ccg/http-signatures#28]
The link is to:

http://www.iana.org/assignments/signature-algorithms

But all I get is a "This page does not exist." webpage from IANA.

**Comment by msporny** [comment]
Yes, this is a known issue, although the whole registry needs to be deprecated due to security concerns. Fixed in https://github.com/w3c-dvcg/http-signatures/commit/e62a249fd776e5897095942d7454489d36419929.

Thanks for the comment!
