### ISSUE TITLE
Clarify behaviour on missing headers in HTTP request/response

### ISSUE THREAD

**Issue by liamdennehy** [w3c-ccg/http-signatures#32]
[Section 2.3](https://tools.ietf.org/html/draft-cavage-http-signatures-10#section-2.3) instructs how to compose the Signature String, but is silent on how to behave when a header is absent (or otherwise does not match a header in the `headers` parameter)

* MUST the header be excluded from the Signature String entirely?
* MUST the header be included in the Signature String with an empty string as header value?
* MUST the condition be considered an error and signing abandoned?

**Comment by lukasz-szewc** [comment]
Personally I like the most restrictive approach: Option nr 3 (MUST the condition be considered an error and signing abandoned?)

**Comment by liamdennehy** [comment]
I agree, as 1 or 2 alter the intention of the signer (who may have no control over the content of the message e.g. at the gateway). I will submit a PR to propose clarified language mandating option 3.

**Comment by liamdennehy** [comment]
Resolved in PR #47
