### ISSUE TITLE
Date header is not mandatory in HTTP/1.1 RFCs yet relied on by "headers" field

### ISSUE THREAD

**Issue by liamdennehy** [w3c-ccg/http-signatures#33]
[IETF RFC 7231](https://tools.ietf.org/html/rfc7231#section-7.1.1.2) ("HTTP") indicates ``Date`` as an optional field in a Request, yet this standard assumes it is always present e.g. it is the default header if no ``headers`` field is provided.

Inclusion of a ``Date`` header should be explicitly stated as a dependency of this protocol for Requests (and Responses, which is already mandatory) rather than assuming it will be provided once an implementer has absorbed the conditions and evaluations of RFC7231 Section 7.1.1.2.

**Comment by msporny** [comment]
Yes, good point. I'll add language to that effect in the next rev of the spec.

**Comment by liamdennehy** [comment]
Thanks! I've seen three different implementations and one standard that mandates usage of this draft, and they all keep claiming Date is "a standard header", not realising that's only for Responses. Most clients don't add a Date header by default, so this leads to way too much confusion.

**Comment by liamdennehy** [comment]
Would a PR be welcome? More than happy to take a shot at some good concise language worthy of a spec like this (even if it means I need to use American spelling).

**Comment by davidlehn** [comment]
PRs are always welcome! ;-)

**Comment by ioggstream** [comment]
@msporny can we close this one?

**Comment by liamdennehy** [comment]
I'm happy with the new approach
