### ISSUE TITLE
Signature header does not contain date, expires

### ISSUE THREAD

**Issue by ioggstream** [w3c-ccg/http-signatures#35]
## I expect

The Signature header to contain the following fields:

  - date
  - expires

Those fields should be part of the Signature and of the signed message.

## Notes

The associated `iss` and `exp` are typical  JWS claims.

**Comment by msporny** [comment]
There is an open issue about specifying "Date" and it being in the default fields that are signed. Some didn't want to use Date, but used a server-provided nonce instead.

What would you expect to happen if "Expires" is included? The server marks the signature as invalid? If so, we expect different applications to have different tolerances for expiration and for the server to determine (if the signature depends on time based validity, and Date is specified), when an acceptable time period is.

We realize that HTTP Signatures could be tightened up a bit, but based on field use, we couldn't put something in there without invalidating some valid use case. Instead, we expect applications to request and enforce the sorts of things you are mentioning (or have specs layered on top of this spec to tighten those requirements down).

**Comment by dlongley** [comment]
Another way to look at the current behavior is that `expires` has the same value as `date` (i.e. it expires immediately) and it therefore does not need to be sent. Sending `expires`, in this light, would only be to extend the validity period further... which is an uncommon use case.

**Comment by ioggstream** [comment]
@msporny iiuc date issue is this one #33 

Let `iat:= issue time` , `exp: expiration time`, `now()` the receiver timestamp

1- imho `iat` and `exp` are properties of the Signature, not of the exchange
2- `Date` is a property of the exchange
3- You should not process the `Signature` if `now() ∉ [iat, exp]`
4- You should not process the `Signature` if  `Date > now()` 



@dlongley if `expires ≡ date` you have the following cases:

  - people will proceed in (imho) broken implementations (eg. https://documentation.ibanity.com/api#signature tolerating 120 seconds of NTP skew ;)

  - ntp mismatch or transmission time of 0.2 seconds

```
>POST /foo HTTP/1.1
>Date: Thu, 30 Aug 2018 08:00:00.800 GMT
>Signature: ...
>...

<HTTP/1.1 400
<Date: Thu, 30 Aug 2018 08:00:01.000 GMT
<
<Signature expired. Issue time was 08:00:00 but now it's 08:00:01  
```

  - cannot process/forward/proxy the signed message (eg asynchronously) as the time is passed


Almost all signature implementations supports an expiration field:

 - https://cloud.google.com/storage/docs/access-control/signed-urls (via `X-AMZ-Expires`)
 - https://docs.aws.amazon.com/general/latest/gr/sigv4-add-signature-to-request.html (via the `Expiration` header)
 - https://tools.ietf.org/html/rfc7519#section-4.1 JWT `iat`, `exp`, `nbf`

**Comment by liamdennehy** [comment]
If I'm only interested in making a signed statement about a particular response rather than create a claim for a specific timeframe, I'd rather not be forced to include an ``expires`` field that has a particular value (e.g. ``0``). I'm much more interested in knowing that a statement was made at an instant, and may not wish to make a specific validity claim (e.g. your balance right now is $100)
If I'm representing a claim, expiry is valuable, but receiving a claim without an expiry would invalidate that claim just as receiving one with an expiry time already lapsed.

This should be optional.

**Comment by ioggstream** [comment]
@liamdennehy OK for optional `expires`. This will improve the situation and avoid  implementors to decide for the timeframe of my signature (see ibanity above).

For responses, we can just set expires with a given timeframe. It should never be set to 0 as this leaves the interpretation to the receiver.

We should think about a way of versioning this signature so we can go on without breaking things and
allow adopters to enforce clearly a more secure version of our standard.

**Comment by liamdennehy** [comment]
I'd like to strengthen my previous comment:
This specification is essentially a free-form mechanism for signing any, all or nothing in a HTTP Message. The comparison was made with JWT which I don't feel is well-founded.
- JWTs are made of three components: A header, indicating how the JWT is to be processed, a payload, and a signature. It is for the explicit purpose of encoding access tokens.
- This specification is more like JWS - that is, useful but meaningless on its' own. The value is the payload which this signature assures, which may or may not include validity periods but crucially it is up to the payload to specify it, or the signer to add one.

If we would like to add token-like fields to the signature header and turn this into a token transport mechanism:

  - It would strongly curtail the utlitity for other applications such as making digitally signed documents or even (non-repudiatable) electronic seals
  - It would imply it is only usable for half the conversation - the one issuing the token or the one using the token.

I would propose we describe optional HTTP Headers (e.g. `X-Signature-Expires`, default to 0 seconds or never depending on token or digital signature use case) that can be included in the headers in the Security Considerations section, but even then we are wading into implementation territory. Any other extensions should first be evaluated as pure HTTP Headers before being considered for inclusion in the Signature header itself.

**Comment by ioggstream** [comment]
Hi Liam, thanks for your reply!

> This specification is more like JWS

partly agree. 

>  [to] turn this into a token transport mechanism..curtail digitally signed documents or electronic seals

iiuc you want a way to state that a signature never expires, right?

> It would imply it is only usable for half the conversation

I don't understand this part. Can you please share an use case?

> we describe optional HTTP Headers (X-Signature-Expires)

- as I see expiration as a signature property (eg. it shouldn't exceed the certificate expiration) this
  seems to me as a workaround ;)
- adding an header means register it to the IANA (consider that the `Signature` header could possible  be register by the signed-exchanges wg) 
- [RFC6648](https://tools.ietf.org/html/rfc6648) deprecates X-headers

### Side discussion follows:
But not really in-topic for the thread;)

> JWTs are made of three components: A header, indicating how the JWT is to be processed, 
> a payload, and a signature. 

iiuc:
  -  JWT is used to represent a set of claims and delegates encoding to the header specified in JW[ES]
  -  The encoding part is in JW[SE], which are just encoded JWT.

> It is for the explicit purpose of encoding access tokens.

  -  While JWT is used for access tokens, I can't find this in JWT specs as an explicit purpose. Instead via JW[SE] you can send signed/encrypted payload too

**Comment by liamdennehy** [comment]
Put simply:
In jws/jwt, attributes of the claim (iat, exp) are payload. Header is purely how to validate the signature (authenticity) of those payload claims.
This protocol might handle signatures with a limited lifetime (ie tokens/claims), instantaneous or indefinitely valid signatures but none of that is relevant to the cryptographic integrity of the signature. My point is the payload (headers, body etc) should encode that data, not the signature line which has a pure, cryptographic validation focus. Including expiration etc mixes technical and meta data purposes.
Quite crucially, including expiry etc in the Signature header means (under the current scheme) it **cannot be secured against tampering**, as it is excluded from the signature itself, so cannot perform its purpose of constraining the validity statement.

**Comment by ioggstream** [comment]
@liamdennehy 

> ... cryptographic integrity of the signature...
> .. the signature line which has a pure, cryptographic validation focus...

I understand the point. The question is how much that leaves space to
bad implementations.

> including expiry etc in the Signature header means (under the current scheme) 
> it cannot be secured against tampering, as it is excluded from the signature itself

Yes, I stated it in the ticket ;)

```
Those fields should be part of the Signature and of the signed message.
```

An interesting implementation is in  [signed-exchanges](https://github.com/WICG/webpackage/blob/master/draft-yasskin-httpbis-origin-signed-exchanges-impl.md)

**Comment by dlongley** [comment]
Note: An advantage to sending "Expires" in the request is that it is not prohibited in browsers (whereas "Date" is).

**Comment by ioggstream** [comment]
@dlongley just read your comment. Are you referring to https://fetch.spec.whatwg.org/#forbidden-header-name ?

Another point for supporting  `date`,`expires` in Signature ;)
