### ISSUE TITLE
Signing String construction - validation logic

### ISSUE THREAD

**Issue by lukasz-szewc** [w3c-ccg/http-signatures#42]
```
2.3.  Signature String Construction

   In order to generate the string that is signed with a key, the client
   MUST use the values of each HTTP header field in the `headers`
   Signature parameter, in the order they appear in the `headers`
   Signature parameter.  It is out of scope for this document to dictate
   what header fields an application will want to enforce, but
   implementers SHOULD at minimum include the request target and Date
   header fields.
```

1. In point 2.1.3 of document there is information to use just `Date` if `headers` are not specified. Let say that this is exactly the case and now during signature string construction there is recommendation to use `request target` as well. Is this recommendation or obligation? (how to understand `SHOULD` in this context - especially when we take into consideration point 2.1.3)
2. Client can produce any HTTP request. (with potentially buggy and inconsistent structure) How should server validate situation (during recreation of signing string) when given header is present on `headers` Signature parameter, but either is not present inside HTTP headers or value of given header is empty ? Should such whole request be treated as invalid or should signing string look like this for example : `missing-header: ""` or `missing-header: ` ?

**Comment by liamdennehy** [comment]
1. It is common convention in RFCs and other technical document to use keywords such as SHOULD, MUST and MUST NOT as defined in [RFC2119](https://tools.ietf.org/html/rfc2119), and it is referenced in the draft specification in section **5.1 Normative References**. Might be an idea to make this more prominent. To answer you question specifically, the statement here is to be interpreted as advice: You SHOULD include these at least, but we're not going to say you MUST.
2. How to handle header(s) specified but not present is an existing open question in #32, go ahead and upvote that issue. As for an empty header value this is allowed in HTTP, though I don't think the language in this specification takes that into account explicitly. As written, the line for that header would be:
`headername: ` (note the trailing space after the colon)

**Comment by liamdennehy** [comment]
@lukasz-szewc Please review PR #47 to see if your questions are properly addressed.

**Comment by liamdennehy** [comment]
@lukasz-szewc PR #47 is merged, would you like to mark this issue resolved?

**Comment by lukasz-szewc** [comment]
@liamdennehy closed
