### ISSUE TITLE
Better Reference Tests

### ISSUE THREAD

**Issue by liamdennehy** [w3c-ccg/http-signatures#43]
In reviewing a few implementations I've come across some pitfalls/misinterpretations. I'd like to propose a new reference case that provides more coverage of the spec:

* Upper and lower case in uri elements (ie signing string construction requires only method and headers are lowercased, not uri or header values) - presently the reference uri is all lowercase.
* Digest header with multiple values ([as permitted in the spec](https://tools.ietf.org/html/rfc3230#section-4.3.2)):
  ``Digest: SHA=abc...,SHA-256=def...``
* Explicitly include signature header strings that include space after comma, or clarify language on formatting to explicitly prohibit this (see #38)
* Enhance body with some further meaning e.g. to illustrate a date in body element makes a different statement (object timestamp) to date in header (transmission timestamp).

I realise updating the reference test is a big deal, so would invite any other clarifications/cases we can illustrate to be included and make this more useful and updated just the once. PR shortly with first draft once I get a few comments.

**Comment by ioggstream** [comment]
For now my 2¢ on point 3 and 4.

On Signature header: is the `Signature` syntax similar to  https://httpwg.org/http-extensions/draft-ietf-httpbis-header-structure.html ? In that case I'd adopt that one.

On `body`: can you pls make an example of a `date in body element`?

Thx++,
R

**Comment by liamdennehy** [comment]
These points are no longer valid, or can be addressed in a more general quality overhaul/review - especially in conjunction with the reference test suite being developed.
