### ISSUE TITLE
header and signature parameters are confusing.

### ISSUE THREAD

**Issue by aljones15** [w3c-ccg/http-signatures#58]
Signature/ Authorization headers contain parameters named header and signature.

however header can contain the values (created) and (expires) which refer to other Signature parameters i.e. created and expires. This means headers really does **not** do what it's name implies.
I think includes might be a better name for headers.

signature is sensical, but easily confusable with the Signature header itself.
I propose verify for the parameter used to store the base64 encoded string.

**Comment by aljones15** [comment]
I'm closing this as it's extremely trivial.

**Comment by liamdennehy** [comment]
> I'm closing this as it's extremely trivial.

You're not the first to notice the complexity of this specification, and we definitely need to work on making it more accessible - clear terms, simple explanations, consistency across every section. I think your observations are valid, and worth addressing.
