### ISSUE TITLE
Don't trust ambiguous parameters

### ISSUE THREAD

**Issue by ioggstream** [w3c-ccg/http-signatures#63]
## I expect

ambiguous parameters should invalidate the signature

eg. this should not be allowed
```
Signature: headers="foo", headers="bar", ...
```

## Instead

they don't invalidate the signature, and the last one is used

https://github.com/w3c-dvcg/http-signatures/blob/8c0bffa3bc0ac71350f9426a0c50aa9b98317bb5/index.xml#L317

eg:
```
Signature: header="bar", ...
```

**Comment by aljones15** [comment]
The existing HTTP spec allows for duplicate headers:

https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2

> Multiple message-header fields with the same field-name MAY be present in a message if and only if the entire field-value for that header field is defined as a comma-separated list [i.e., #(values)]. It MUST be possible to combine the multiple header fields into one "field-name: field-value" pair, without changing the semantics of the message, by appending each subsequent field-value to the first, each separated by a comma. The order in which header fields with the same field-name are received is therefore significant to the interpretation of the combined field value, and thus a proxy MUST NOT change the order of these field values when a message is forwarded.

If the HTML spec allows it it might cause issues as another piece of middleware might collate duplicate headers into a list etc. Duplicate header names is a feature of HTML Messages, throwing on duplicate headers could cause issues with other programs that use the headers. I guess we consider them ambiguous other programs consider them lists.

**Comment by ioggstream** [comment]
## Case 1: Ambiguous parameters refers to multiple HTTP headers

@aljones15 the HTTP spec is now [rfc7230#field-order](https://tools.ietf.org/html/rfc7230#section-3.2.2)

> A sender MUST NOT generate multiple header fields with the same field
   name in a message unless either the entire field value for that
   header field is defined as a comma-separated list

Let's say a sender sends

```
Content-Language: mi
Content-Language: en
Signature: headers="content-language content-language", ...
```
iiuc a `recipient` which acts as an  [intermediary](https://tools.ietf.org/html/rfc7230#section-2.3), can lawfully 

>  A recipient MAY combine multiple header fields with the same field
   name into one "field-name: field-value" pair, without changing the
   semantics of the message, by appending each subsequent field value to
   the combined field value in order, separated by a comma. 

which leads to 

```
Content-Language: mi, en
Signature: headers="content-language content-language", ...
```
This invalidates the signature.

## Case 2. Ambiguous parameters refers to the `Signature` header

If Ambiguous Parameters refers to the `Signature` header, eg.

```
Signature: headers="(request-target)", keyId="1234",  headers="(request-target)", ...
```

then imho it's safe *not to trust* that Signature and even avoid processing it rather than trying to interpret that

**Comment by ioggstream** [comment]
@aljones15 in any case, we should clarify that

**Comment by aljones15** [comment]
@ioggstream for what it is worth I believe ambiguous parameters here does refer to parameters as in Case 2 (I guess I was wrong) as the spec deals with duplicate http headers:

> If there are multiple instances of the same header field, all header field
> values associated with the header field MUST be concatenated, separated by a
> ASCII comma and an ASCII space `, `, and used in the order in which
> they will appear in the transmitted HTTP message.

may bad should have spent a little more time before replying. I actually kind of agree with this issue regarding Case 2 as we have plenty of control over the contents of the parameters to the Signature or Authorization header field.

**Comment by ioggstream** [comment]
@aljones15 
> should have spent a little more time before replying

no problem, at least this brought an useful discussion. I agree that the text is not straightforward and it's worth to clarify that. 

Can we say we shouldn't trust ambiguous `Signature headers` parameters?

**Comment by ioggstream** [comment]
@liamdennehy if you agree in removing ambiguous cases, I'll provide a PR.

**Comment by liamdennehy** [comment]
The word "erroneously" is troublesome, as it implies the verifier should be able to tell what was intentional and what was erroneous - hence the "if". I'd simply state that any parameter duplicated in the Signature line invalidates the entire signature.

**Comment by liamdennehy** [comment]
As for multiple occurrences of a header in a message and how we incorporate that in a signature;

While HTTP does permit duplicates, concatenating the value in the signature string can lead to ambiguity of interpretation - two headers with different values is semantically different to a header with two values. Since we cannot reliably interpret the intent of the sender and form a canonical signature string (headers may be reordered, headers added without the signer's knowledge) we should simply refuse to process signatures that rely on duplicate headers.

This does break some compatibility with HTTP messages, but I don't see the risk being worth it. Cryptographic breaks thrive on ambiguities and interpretation.

**Comment by ioggstream** [comment]
@liamdennehy will #65 work for you? 

> The word "erroneously" is troublesome

Agree, feel free to propose changes to #65 

> As for multiple occurrences of a header in a message

I'd continue discussing it on #50: I'll copy previous considerations there.

**Comment by ioggstream** [comment]
Can we get some consensus on #63?
