### ISSUE TITLE
Status of this RFC related to European PSD2 (Berlin group) ?

### ISSUE THREAD

**Issue by earroyoron** [w3c-ccg/http-signatures#64]
Hi,
The European Payments Directive (PSD2) mandates via their RTS (Regulatory Technical Standards) some security mechanism to identify parties, using a certificate with some extensions, called eIDAS. The Berlin Group has defined a technical approach for all this regulation that is a REST API and includes this RFC as a technical solution to comply with these standards etc.
I am wondering about the status of this RFC because the PSD2 deadlines are clear (14th September 2019) and also I ask myself about what does this RFC apport to a TLS mutual authentication scheme which is what I was though in first is asked...
THANKS A LOT.

**Comment by ioggstream** [comment]
Hi Ernesto,

with some agencies we are working to contributo to draft-cavage as a signature mechanism for psd2 and for use in cross-border exchanges.

Here's a gdoc for http-signatures:

- https://docs.google.com/document/d/1EHOcsZmKodlgodMZo4zdhEBLBjZRyeFB1BeOsQEzrDw/

Meanwhile we are rewriting the http Digest header specs to clarify its usage in signatures (below):

- https://github.com/ioggstream/draft-polli-resource-digests-http

**Comment by earroyoron** [comment]
Eurobits (the company where I work at) is one of the most active parties in PSD2 in Europe, and we may be interested to help and collaborate in this RFC, as I don't find a "contribution guide" here, may you please tell me if this is possible and how?
E.g. a "reference implementation" for example is an idea, but  any other task etc

**Comment by ioggstream** [comment]
@earroyoron the maintainer of the spec is Manu @msporny, which works on many different specs.

I'm working for the Italian Digital Transformation Team. My goal is to check if this spec can be consolidated in a way that is suitable for adoption by agencies in Italy and Europe.

To contribute, I just joined the discussion on github, while using the gdoc as a helper. In case, feel free to email me.

**Comment by liamdennehy** [comment]
@earroyoron This specification predated Berlin Group's proposals, and accounts for use cases well beyond PKI. As such, I've been contributing here to see that the specification continues to support Berlin Group (where it is *optional*) and PSD2 in general, but explicitly avoid tailoring it too narrowly for that purpose. It is disappointing Berlin Group have not collaborated directly, but it is their choice.

This specification has no solid date for being adopted as a standard IETF RFC, and almost certainly won't be ready by October. Be aware that adopting any draft of this signature specification before it is published is at the risk of the PSP, especially in the context of chapter 21 of the PSD2 RTS on SCA, as this draft specification is not yet a standard.

**Comment by ioggstream** [comment]
> I ask myself about what does this RFC apport to a TLS mutual authentication scheme which is what I was though in first is asked...

I think signing certificates and TLS certificates should be different though. Isn't it?

**Comment by earroyoron** [comment]
Yes you are right @ioggstream , the MTLS certificate should be trusted by network endpoint, and this header-signing is more about "business" (your application) with a complete different requirements.
 🤔 actually that could be the answer.

**Comment by liamdennehy** [comment]
@earroyoron @ioggstream 

The directive and the RTS require only that TPPs _identify_ themselves to ASPSPs. Mutual TLS proves the connection is initiated by the holder of a certificate's private key, while a digital signature in the message (either using this specification or another such as JWS) both proves the identity of the message/payload creator *and* proof of authenticity (it has not been altered).

Note that the second proof (authenticity) is not required under the RTS, so MTLS with a QWAC may be sufficient. Berlin Group using this specification (and some bank-specific implementations that do not use this specification but something similar of their own creation) may provide some measure of authenticity, but this is beyond what the EBA requires.

Note: I am not a lawyer, but have been having this conversation with actual lawyers, QTSPs, NCAs and ENISA themselves for months. If in doubt, consult an actual lawyer. This is not just a technical curiosity, it has real consequences in terms of risk and liability.

**Comment by liamdennehy** [comment]
@earroyoron As this issue does not have any action required to resolve, do you want to ask further questions or can this issue be closed?

**Comment by earroyoron** [comment]
I think you can close as the questions we may have are not related to the RFC but to the PSD2 or RTS and this is not the forum...
So yes, close this
And thanks a lot
