### ISSUE TITLE
PROPOSAL: move index.xml to index.md

### ISSUE THREAD

**Issue by ioggstream** [w3c-ccg/http-signatures#71]
## I propose

To move the index.xml to an index.md

## This is

Could help readability and ease contributions.

**Comment by davidlehn** [comment]
The IETF uses XML source files for RFCs.  See RFC2629 (and newer).  There has been work on a markdown syntax and related tools, but I don't know the status of those.

To do any change, someone would have to research the latest RFC markdown flavor style and tools, see if it's possible to convert from XML, check if the tools work and produce correct results, and determine if the markdown editing flow is better than the current XML flow.  It does seem easy enough right now to use minimal tools and just load up the xml file in a browser and let the xsl make it look nice.

**Comment by liamdennehy** [comment]
@ioggstream, as nice as it would be to submit in markdown, for now the workflows are all designed around the XML representation and it's unlikely we can change this any time soon.
