### ISSUE TITLE
Signatures in C.1 are incorrect

### ISSUE THREAD

**Issue by bblfish** [w3c-ccg/http-signatures#9]
In [C.1 Default Test](https://w3c-dvcg.github.io/http-signatures/#default-test) it is written that the string to sign would be

```
date: Thu, 05 Jan 2014 21:31:40 GMT
```

But that date is not a Thursday, but a Sunday, as you can verify both on [TimeAndDate.com calendar for that month](https://www.timeanddate.com/calendar/monthly.html?year=2014&month=1&country=9) or as I did whilst attempting to build a test for this in [commit afc82... of akka-http-signature](https://github.com/read-write-web/akka-http-signature/blob/afc827af0ba9f585f19d49abd12ba7b3ad2f9f6e/src/test/scala/run/cosy/auth/HttpSignatureSpecTest.scala#L155)

```scala
HttpRequest(HttpMethod(GET),/foo,List(Date: Sun, 05 Jan 2014 21:31:40 GMT),HttpEntity.Strict(none/none,ByteString()),HttpProtocol(HTTP/1.1))
```

Furthermore, it looks like the signature does not match the expected one for either the correct date or the fictional one. 

The spec mentions that the signature to be expected should be:

```HTTP
Authorization: Signature keyId="Test",algorithm="rsa-sha256",
signature="ATp0r26dbMIxOopqw0OfABDT7CKMIoENumuruOtarj8n/97Q3htH
FYpH8yOSQk3Z5zh8UxUym6FYTb5+A0Nz3NRsXJibnYi7brE/4tx5But9kkFGzG+
xpUmimN4c3TMN7OFH//+r8hBf7BT9/GmHDUVZT2JzWGLZES2xDOUuMtA="
```

All my initial tests pass but not the one that tries to match the signature of the fictional date to what the specification expects. See [HttpSignatureSpecTest line 195](https://github.com/read-write-web/akka-http-signature/blob/b9c8d4787bf4cb447f5b984c10f045653b4f48ca/src/test/scala/run/cosy/auth/HttpSignatureSpecTest.scala#L195).

The signature I actually get is:

```
jKyvPcxB4JbmYY4mByyBY7cZfNl4OW9HpFQlG7N4YcJPteKTu4MWCLyk+gIr0wDgqtLWf9NLpMAMimdfsH7FSWGfbMFSrsVTHNTk0rK3usrfFnti1dxsM4jl0kYJCKTGI/UWkqiaxwNiKqGcdlEDrTcUhhsFsOIo8VhddmZTZ8w=
```

**Comment by bblfish** [comment]
Btw having a fictional date would not necessarily be a bad thing, if the text were a little more clear about that (I can propose some better phrasing), as it helps focus the implementers mind.

On the other hand the signatures should be correct. (But it might be that my code is broken -- I was having trouble loading the public and private keys, as can be seen from the code)

**Comment by bblfish** [comment]
oops it's late. I did not mean to close this.

**Comment by bblfish** [comment]
The commit above, in addition to the reasoning that follows

1. prove the spec has a bug
2. find the cause of it
3. show what the right answers might be.

[The first test](https://github.com/read-write-web/akka-http-signature/blob/d76686a00db462f63bcd34227a60edc3accc34d6/src/test/scala/run/cosy/auth/HttpSignatureSpecTest.scala#L199) shows that the signature matches that of a different date, namely

```
date: Thu, 05 Jan 2012 21:31:40 GMT
```

Now before you start thinking I have broken RSA - which I would love you to think even for just a second ;-D  - wondering how I found the date that matched the signature, let me tell you that I did a little digging around...

Note, by the way, that the date is real and that indeed "5 Jan 2012" was a Thursday as you can verify on the [time and date site](https://www.timeanddate.com/calendar/monthly.html?year=2012&month=1&country=9).
 
I found where the spec bug came from. It's very likely a copy and paste mistake. You copied the signature from the [JS test](https://github.com/joyent/node-http-signature/blob/master/test/verify.test.js#L298) with the above date, and presumably then took the date of the next test, which matches a different signature - namely the one in the test.

Indeed [I wrote a test for the fictional date](https://github.com/read-write-web/akka-http-signature/blob/d76686a00db462f63bcd34227a60edc3accc34d6/src/test/scala/run/cosy/auth/HttpSignatureSpecTest.scala#L211) that matches the signature in the joyent test for that fictional date.

Finally, I also calculated and tested the signature for [the actual date of the 5th Jan 2014](https://github.com/read-write-web/akka-http-signature/blob/d76686a00db462f63bcd34227a60edc3accc34d6/src/test/scala/run/cosy/auth/HttpSignatureSpecTest.scala#L224).

Possible fixes are:
 1. change the header to be signed to `date: Thu, 05 Jan 2012 21:31:40 GMT` which is real and not change the signature
 2. change the signature for the fictional date to the one indicated in the tests, and change the spec text a little more to indicate subtly that this is a fictional date. This is useful in that it can help capture errors that could come from parsing a header into a date and then reconstituting the signature from that, rather than from the given date. Ie. It would force someone to test the string first ( and not test the Date implementation on his platform ). But it would also get the engineer to think about the danger of fake dates: ie someone could try a signature and see if they could find a  weakness to find a date that would match a found signature and try to send that at the appropriate moment.

**Comment by wrygiel** [comment]
The following quotes were moved here from an email message (`Message-ID: <93749dce-491c-11ea-2038-b46e36985710@digitalbazaar.com>`).

On Wed, Oct 18, 2017 at 5:40 PM, Manu Sporny wrote:
> On 10/18/2017 11:25 AM, Wojtek Rygielski wrote:
>> Hello,
>>
>> I was getting an error while writing unit tests for a system in
>> which we plan to use HTTP Signatures. After some debugging, I now
>> believe that the error originates not from the code, but from the
>> specs (which I have used for test values).
>>
>> In "Appendix C. Test Values" section, the specs make use of the
>> following header:
>>
>> Date: Thu, 05 Jan 2014 21:31:40 GMT
>>
>> I believe it should instead be:
>>
>> Date: Sun, 05 Jan 2014 21:31:40 GMT
>>
> 
> Apologies, this bug in the spec has bitten a number of implementers and
> is being tracked here:
> 
> https://github.com/w3c-dvcg/http-signatures/issues/9

Thanks! I wasn't aware this repository exists.

> I'm slammed these days and have little time to update the spec. If you
> could submit a PR to fix this issue, that would be great.

Sure, I think I'll find some time for that.

> Also, are you doing an implementation?

Not yet, but I'm thoroughly testing the existing ones.

(What I'm writing is an "online validator" tool for [EWP Network](https://developers.erasmuswithoutpaper.eu/). Given an URL, it will run a battery of tests on it. We use HTTP Signatures for both [client](https://github.com/erasmus-without-paper/ewp-specs-sec-cliauth-httpsig) and [server](https://github.com/erasmus-without-paper/ewp-specs-sec-srvauth-httpsig) authentication.)
